/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.scm.client.shop.view;

import java.text.NumberFormat;

/**
 *
 * @author Mathan
 */
public class ShopView extends javax.swing.JPanel {

    NumberFormat format = NumberFormat.getNumberInstance();
    /**
     * Creates new form CreateShopUI
     */
    public ShopView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        groupNameCbx = new javax.swing.JComboBox();
        groupNameLbl = new javax.swing.JLabel();
        sqfeetRateLbl = new javax.swing.JLabel();
        shopNoLbl = new javax.swing.JLabel();
        totalSqlfeetTxt = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        sqFtRateTxt = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        totalSqfeetLbl = new javax.swing.JLabel();
        shopNoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cancelBtn.setBackground(new java.awt.Color(153, 204, 255));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");

        saveBtn.setBackground(new java.awt.Color(153, 204, 255));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");

        groupNameLbl.setText("Group Name");

        sqfeetRateLbl.setText("Sq.ft Rate");

        shopNoLbl.setText("Shop No");

        totalSqfeetLbl.setText("Total Sq.ft");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sqfeetRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(sqFtRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalSqfeetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(totalSqlfeetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(shopNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(shopNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(groupNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(groupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopNoLbl)
                    .addComponent(shopNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameLbl)
                    .addComponent(groupNameCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqfeetRateLbl)
                    .addComponent(sqFtRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSqfeetLbl)
                    .addComponent(totalSqlfeetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Create Shop Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox groupNameCbx;
    private javax.swing.JLabel groupNameLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel shopNoLbl;
    private javax.swing.JTextField shopNoTxt;
    private javax.swing.JFormattedTextField sqFtRateTxt;
    private javax.swing.JLabel sqfeetRateLbl;
    private javax.swing.JLabel totalSqfeetLbl;
    private javax.swing.JFormattedTextField totalSqlfeetTxt;
    // End of variables declaration//GEN-END:variables
	public NumberFormat getFormat() {
		return format;
	}

	public void setFormat(NumberFormat format) {
		this.format = format;
	}

	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	public javax.swing.JComboBox getGroupNameCbx() {
		return groupNameCbx;
	}

	public void setGroupNameCbx(javax.swing.JComboBox groupNameCbx) {
		this.groupNameCbx = groupNameCbx;
	}

	public javax.swing.JLabel getGroupNameLbl() {
		return groupNameLbl;
	}

	public void setGroupNameLbl(javax.swing.JLabel groupNameLbl) {
		this.groupNameLbl = groupNameLbl;
	}

	public javax.swing.JButton getSaveBtn() {
		return saveBtn;
	}

	public void setSaveBtn(javax.swing.JButton saveBtn) {
		this.saveBtn = saveBtn;
	}

	public javax.swing.JLabel getShopNoLbl() {
		return shopNoLbl;
	}

	public void setShopNoLbl(javax.swing.JLabel shopNoLbl) {
		this.shopNoLbl = shopNoLbl;
	}

	public javax.swing.JTextField getShopNoTxt() {
		return shopNoTxt;
	}

	public void setShopNoTxt(javax.swing.JTextField shopNoTxt) {
		this.shopNoTxt = shopNoTxt;
	}

	public javax.swing.JFormattedTextField getSqFtRateTxt() {
		return sqFtRateTxt;
	}

	public void setSqFtRateTxt(javax.swing.JFormattedTextField sqFtRateTxt) {
		this.sqFtRateTxt = sqFtRateTxt;
	}

	public javax.swing.JLabel getSqfeetRateLbl() {
		return sqfeetRateLbl;
	}

	public void setSqfeetRateLbl(javax.swing.JLabel sqfeetRateLbl) {
		this.sqfeetRateLbl = sqfeetRateLbl;
	}

	public javax.swing.JLabel getTotalSqfeetLbl() {
		return totalSqfeetLbl;
	}

	public void setTotalSqfeetLbl(javax.swing.JLabel totalSqfeetLbl) {
		this.totalSqfeetLbl = totalSqfeetLbl;
	}

	public javax.swing.JFormattedTextField getTotalSqlfeetTxt() {
		return totalSqlfeetTxt;
	}

	public void setTotalSqlfeetTxt(javax.swing.JFormattedTextField totalSqlfeetTxt) {
		this.totalSqlfeetTxt = totalSqlfeetTxt;
	}


}
