/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fixent.scm.client.tenant.view;

import java.text.NumberFormat;

/**
 *
 * @author Mathan
 */
public class TenantView extends javax.swing.JPanel {

    /**
     * Creates new form CreateTenantUI
     */
    public TenantView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        shopNoCbx = new javax.swing.JComboBox();
        cityTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        mobileNoLbl = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        shopNoLbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        streetTxt = new javax.swing.JTextArea();
        tenantNameLbl = new javax.swing.JLabel();
        landdlineNoLbl = new javax.swing.JLabel();
        tenantAddressLbl = new javax.swing.JLabel();
        shopNameTxt = new javax.swing.JTextField();
        landdlineNoLbl1 = new javax.swing.JLabel();
        stateTxt = new javax.swing.JTextField();
        landdlineNoLbl2 = new javax.swing.JLabel();
        landdlineNoLbl3 = new javax.swing.JLabel();
        pinCodeTxt = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        mobileNoTxt = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        landlineNoTxt = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        statusLbl.setText("Shop Name");

        mobileNoLbl.setText("Mobile No.");

        saveBtn.setBackground(new java.awt.Color(153, 204, 255));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");

        shopNoLbl.setText("Shop No");

        cancelBtn.setBackground(new java.awt.Color(153, 204, 255));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");

        streetTxt.setColumns(20);
        streetTxt.setRows(5);
        jScrollPane2.setViewportView(streetTxt);

        tenantNameLbl.setText("Name");

        landdlineNoLbl.setText("City");

        tenantAddressLbl.setText("Street");

        landdlineNoLbl1.setText("State");

        landdlineNoLbl2.setText("Pin Code");

        landdlineNoLbl3.setText("Landline No.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(shopNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(shopNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(shopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tenantAddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(landdlineNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cityTxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(mobileNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mobileNoTxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tenantNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(landdlineNoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(stateTxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(landdlineNoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pinCodeTxt))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(landdlineNoLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(landlineNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenantNameLbl)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenantAddressLbl))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landdlineNoLbl)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landdlineNoLbl1)
                    .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landdlineNoLbl2)
                    .addComponent(pinCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landdlineNoLbl3)
                    .addComponent(landlineNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileNoLbl)
                    .addComponent(mobileNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shopNoLbl)
                    .addComponent(shopNoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(shopNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(saveBtn))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Tenant Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel landdlineNoLbl;
    private javax.swing.JLabel landdlineNoLbl1;
    private javax.swing.JLabel landdlineNoLbl2;
    private javax.swing.JLabel landdlineNoLbl3;
    private javax.swing.JFormattedTextField landlineNoTxt;
    private javax.swing.JLabel mobileNoLbl;
    private javax.swing.JFormattedTextField mobileNoTxt;
    private javax.swing.JFormattedTextField pinCodeTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField shopNameTxt;
    private javax.swing.JComboBox shopNoCbx;
    private javax.swing.JLabel shopNoLbl;
    private javax.swing.JTextField stateTxt;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextArea streetTxt;
    private javax.swing.JLabel tenantAddressLbl;
    private javax.swing.JLabel tenantNameLbl;
    // End of variables declaration//GEN-END:variables
	public javax.swing.JTextField getNameTxt() {
		return NameTxt;
	}

	public void setNameTxt(javax.swing.JTextField nameTxt) {
		NameTxt = nameTxt;
	}

	public javax.swing.JButton getCancelBtn() {
		return cancelBtn;
	}

	public void setCancelBtn(javax.swing.JButton cancelBtn) {
		this.cancelBtn = cancelBtn;
	}

	public javax.swing.JTextField getCityTxt() {
		return cityTxt;
	}

	public void setCityTxt(javax.swing.JTextField cityTxt) {
		this.cityTxt = cityTxt;
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public javax.swing.JScrollPane getjScrollPane2() {
		return jScrollPane2;
	}

	public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
		this.jScrollPane2 = jScrollPane2;
	}

	public javax.swing.JLabel getLanddlineNoLbl() {
		return landdlineNoLbl;
	}

	public void setLanddlineNoLbl(javax.swing.JLabel landdlineNoLbl) {
		this.landdlineNoLbl = landdlineNoLbl;
	}

	public javax.swing.JLabel getLanddlineNoLbl1() {
		return landdlineNoLbl1;
	}

	public void setLanddlineNoLbl1(javax.swing.JLabel landdlineNoLbl1) {
		this.landdlineNoLbl1 = landdlineNoLbl1;
	}

	public javax.swing.JLabel getLanddlineNoLbl2() {
		return landdlineNoLbl2;
	}

	public void setLanddlineNoLbl2(javax.swing.JLabel landdlineNoLbl2) {
		this.landdlineNoLbl2 = landdlineNoLbl2;
	}

	public javax.swing.JLabel getLanddlineNoLbl3() {
		return landdlineNoLbl3;
	}

	public void setLanddlineNoLbl3(javax.swing.JLabel landdlineNoLbl3) {
		this.landdlineNoLbl3 = landdlineNoLbl3;
	}

	public javax.swing.JFormattedTextField getLandlineNoTxt() {
		return landlineNoTxt;
	}

	public void setLandlineNoTxt(javax.swing.JFormattedTextField landlineNoTxt) {
		this.landlineNoTxt = landlineNoTxt;
	}

	public javax.swing.JLabel getMobileNoLbl() {
		return mobileNoLbl;
	}

	public void setMobileNoLbl(javax.swing.JLabel mobileNoLbl) {
		this.mobileNoLbl = mobileNoLbl;
	}

	public javax.swing.JFormattedTextField getMobileNoTxt() {
		return mobileNoTxt;
	}

	public void setMobileNoTxt(javax.swing.JFormattedTextField mobileNoTxt) {
		this.mobileNoTxt = mobileNoTxt;
	}

	public javax.swing.JFormattedTextField getPinCodeTxt() {
		return pinCodeTxt;
	}

	public void setPinCodeTxt(javax.swing.JFormattedTextField pinCodeTxt) {
		this.pinCodeTxt = pinCodeTxt;
	}

	public javax.swing.JButton getSaveBtn() {
		return saveBtn;
	}

	public void setSaveBtn(javax.swing.JButton saveBtn) {
		this.saveBtn = saveBtn;
	}

	public javax.swing.JTextField getShopNameTxt() {
		return shopNameTxt;
	}

	public void setShopNameTxt(javax.swing.JTextField shopNameTxt) {
		this.shopNameTxt = shopNameTxt;
	}

	public javax.swing.JComboBox getShopNoCbx() {
		return shopNoCbx;
	}

	public void setShopNoCbx(javax.swing.JComboBox shopNoCbx) {
		this.shopNoCbx = shopNoCbx;
	}

	public javax.swing.JLabel getShopNoLbl() {
		return shopNoLbl;
	}

	public void setShopNoLbl(javax.swing.JLabel shopNoLbl) {
		this.shopNoLbl = shopNoLbl;
	}

	public javax.swing.JTextField getStateTxt() {
		return stateTxt;
	}

	public void setStateTxt(javax.swing.JTextField stateTxt) {
		this.stateTxt = stateTxt;
	}

	public javax.swing.JLabel getStatusLbl() {
		return statusLbl;
	}

	public void setStatusLbl(javax.swing.JLabel statusLbl) {
		this.statusLbl = statusLbl;
	}

	public javax.swing.JTextArea getStreetTxt() {
		return streetTxt;
	}

	public void setStreetTxt(javax.swing.JTextArea streetTxt) {
		this.streetTxt = streetTxt;
	}

	public javax.swing.JLabel getTenantAddressLbl() {
		return tenantAddressLbl;
	}

	public void setTenantAddressLbl(javax.swing.JLabel tenantAddressLbl) {
		this.tenantAddressLbl = tenantAddressLbl;
	}

	public javax.swing.JLabel getTenantNameLbl() {
		return tenantNameLbl;
	}

	public void setTenantNameLbl(javax.swing.JLabel tenantNameLbl) {
		this.tenantNameLbl = tenantNameLbl;
	}
    
}
