
CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(30) NOT NULL,
  PASSWORD varchar(30) NOT NULL,
  FIRST_NAME varchar(30) NOT NULL,
  MIDDLE_NAME varchar(30) DEFAULT NULL,
  LAST_NAME varchar(30) DEFAULT NULL,
  EMAIL varchar(30) DEFAULT NULL,
  CREATED_BY varchar(30) DEFAULT NULL,
  CREATED_DATE date DEFAULT NULL,
  UPDATED_BY varchar(30) DEFAULT NULL,
  UPDATED_DATE date DEFAULT NULL,
  PRIMARY KEY (id)
) 



CREATE TABLE shop_group (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  PRIMARY KEY (ID)
) 



CREATE TABLE shop (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  SQRT_FEET decimal(11,0) NOT NULL,
  RENT_PER_SQRT_FEET decimal(11,0) NOT NULL,
  GROUP_ID int(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_GROUP_ID_idx (GROUP_ID),
  CONSTRAINT FK_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES shop_group (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) 


CREATE TABLE tenant (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  MOBILE_NUMBER int(10) DEFAULT NULL,
  BOOKING_DATE date DEFAULT NULL,
  ADVANCE_AMOUNT decimal(10,0) DEFAULT NULL,
  LAST_DUE_DATE date DEFAULT NULL,
  NEXT_DUE_DATE date DEFAULT NULL,
  BALANCE_PAYMENT decimal(10,0) DEFAULT NULL,
  EXTRA_PAYMENT decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (ID)
) 

