package com.fixent.scm.server.model;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rent.java
//  @ Date : 9/8/2013
//  @ Author : 
//
//




public class Rent {
	private int id;
	private Double advanceAmount;
	private Double excessPayment;
	private Date bookingDate;
	private Shop shop;
	private Tenant tenant;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Double getAdvanceAmount() {
		return advanceAmount;
	}
	public void setAdvanceAmount(Double advanceAmount) {
		this.advanceAmount = advanceAmount;
	}
	public Double getExcessPayment() {
		return excessPayment;
	}
	public void setExcessPayment(Double excessPayment) {
		this.excessPayment = excessPayment;
	}
	public Date getBookingDate() {
		return bookingDate;
	}
	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}
	public Shop getShop() {
		return shop;
	}
	public void setShop(Shop shop) {
		this.shop = shop;
	}
	public Tenant getTenant() {
		return tenant;
	}
	public void setTenant(Tenant tenant) {
		this.tenant = tenant;
	}
	
	
}
