package com.fixent.scm.server.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rent.java
//  @ Date : 9/7/2013
//  @ Author : 
//
//




public class Rent {
	private Double excessAmount;
	private Shop shop;
	private Tenant tenant;
	public Double getExcessAmount() {
		return excessAmount;
	}
	public void setExcessAmount(Double excessAmount) {
		this.excessAmount = excessAmount;
	}
	public Shop getShop() {
		return shop;
	}
	public void setShop(Shop shop) {
		this.shop = shop;
	}
	public Tenant getTenant() {
		return tenant;
	}
	public void setTenant(Tenant tenant) {
		this.tenant = tenant;
	}
	
	
}
