package com.fixent.scm.server.model;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rent.java
//  @ Date : 9/2/2013
//  @ Author : 
//
//




public class Rent {
	
	private long currentDue;
	private long previousDue;
	private long dueAmount;
	private long paymentAmount;
	private Date dueDate;
	private Date paymentDate;
	private long balancePayment;
	private long eccessPayment;
	private Shop shop;
	private Tenant tenant;
	public long getCurrentDue() {
		return currentDue;
	}
	public void setCurrentDue(long currentDue) {
		this.currentDue = currentDue;
	}
	public long getPreviousDue() {
		return previousDue;
	}
	public void setPreviousDue(long previousDue) {
		this.previousDue = previousDue;
	}
	public long getDueAmount() {
		return dueAmount;
	}
	public void setDueAmount(long dueAmount) {
		this.dueAmount = dueAmount;
	}
	public long getPaymentAmount() {
		return paymentAmount;
	}
	public void setPaymentAmount(long paymentAmount) {
		this.paymentAmount = paymentAmount;
	}
	public Date getDueDate() {
		return dueDate;
	}
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}
	public Date getPaymentDate() {
		return paymentDate;
	}
	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}
	public long getBalancePayment() {
		return balancePayment;
	}
	public void setBalancePayment(long balancePayment) {
		this.balancePayment = balancePayment;
	}
	public long getEccessPayment() {
		return eccessPayment;
	}
	public void setEccessPayment(long eccessPayment) {
		this.eccessPayment = eccessPayment;
	}
	public Shop getShop() {
		return shop;
	}
	public void setShop(Shop shop) {
		this.shop = shop;
	}
	public Tenant getTenant() {
		return tenant;
	}
	public void setTenant(Tenant tenant) {
		this.tenant = tenant;
	}
	
	
}
