package com.fixent.scm.server.model;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Schedule.java
//  @ Date : 9/8/2013
//  @ Author : 
//
//




public class Schedule {
	private int id;
	private Date lastDueDate;
	private Date dueDate;
	public Object dueAmount;
	private Double paymentDate;
	private Double paymentAmount;
	public Rent rent;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Date getLastDueDate() {
		return lastDueDate;
	}
	public void setLastDueDate(Date lastDueDate) {
		this.lastDueDate = lastDueDate;
	}
	public Date getDueDate() {
		return dueDate;
	}
	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}
	public Object getDueAmount() {
		return dueAmount;
	}
	public void setDueAmount(Object dueAmount) {
		this.dueAmount = dueAmount;
	}
	public Double getPaymentDate() {
		return paymentDate;
	}
	public void setPaymentDate(Double paymentDate) {
		this.paymentDate = paymentDate;
	}
	public Double getPaymentAmount() {
		return paymentAmount;
	}
	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}
	public Rent getRent() {
		return rent;
	}
	public void setRent(Rent rent) {
		this.rent = rent;
	}
	
}
