package com.fixent.scm.server.model;

import java.util.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Schedule.java
//  @ Date : 9/7/2013
//  @ Author : 
//
//




public class Schedule {
	private int id;
	private Double nextDueDate;
	private Double nextDueAmount;
	private Double paymentDate;
	private Double paymentAmount;
	private Date lastDueDate;
	private Double lastDueAmount;
	public Rent rent;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Double getNextDueDate() {
		return nextDueDate;
	}
	public void setNextDueDate(Double nextDueDate) {
		this.nextDueDate = nextDueDate;
	}
	public Double getNextDueAmount() {
		return nextDueAmount;
	}
	public void setNextDueAmount(Double nextDueAmount) {
		this.nextDueAmount = nextDueAmount;
	}
	public Double getPaymentDate() {
		return paymentDate;
	}
	public void setPaymentDate(Double paymentDate) {
		this.paymentDate = paymentDate;
	}
	public Double getPaymentAmount() {
		return paymentAmount;
	}
	public void setPaymentAmount(Double paymentAmount) {
		this.paymentAmount = paymentAmount;
	}
	public Date getLastDueDate() {
		return lastDueDate;
	}
	public void setLastDueDate(Date lastDueDate) {
		this.lastDueDate = lastDueDate;
	}
	public Double getLastDueAmount() {
		return lastDueAmount;
	}
	public void setLastDueAmount(Double lastDueAmount) {
		this.lastDueAmount = lastDueAmount;
	}
	public Rent getRent() {
		return rent;
	}
	public void setRent(Rent rent) {
		this.rent = rent;
	}
	
	
}
