package com.fixent.scm.server.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shop.java
//  @ Date : 9/2/2013
//  @ Author : 
//
//




public class Shop {
	
	private int id;
	private String name;
	private long sqrtFeet;
	private long rentPerSqrtFeet;
	private ShopGroup group;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public long getSqrtFeet() {
		return sqrtFeet;
	}
	public void setSqrtFeet(long sqrtFeet) {
		this.sqrtFeet = sqrtFeet;
	}
	public long getRentPerSqrtFeet() {
		return rentPerSqrtFeet;
	}
	public void setRentPerSqrtFeet(long rentPerSqrtFeet) {
		this.rentPerSqrtFeet = rentPerSqrtFeet;
	}
	public ShopGroup getGroup() {
		return group;
	}
	public void setGroup(ShopGroup group) {
		this.group = group;
	}
	
	
}
