package com.fixent.scm.server.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Shop.java
//  @ Date : 9/8/2013
//  @ Author : 
//
//




public class Shop {
	private int number;
	private Double sqrtFeet;
	private Double rentPerSqrtFeet;
	private ShopGroup group;
	
	public int getNumber() {
		return number;
	}
	public void setNumber(int number) {
		this.number = number;
	}
	public Double getSqrtFeet() {
		return sqrtFeet;
	}
	public void setSqrtFeet(Double sqrtFeet) {
		this.sqrtFeet = sqrtFeet;
	}
	public Double getRentPerSqrtFeet() {
		return rentPerSqrtFeet;
	}
	public void setRentPerSqrtFeet(Double rentPerSqrtFeet) {
		this.rentPerSqrtFeet = rentPerSqrtFeet;
	}
	public ShopGroup getGroup() {
		return group;
	}
	public void setGroup(ShopGroup group) {
		this.group = group;
	}
	
}
