package com.fixent.scm.server.model;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tenant.java
//  @ Date : 9/2/2013
//  @ Author : 
//
//




public class Tenant {
	
	private int id;
	private String name;
	private int mobileNumber;
	private Date bookingDate;
	private long advanceAmount;
	private Date lastDueDate;
	private Date nextDueDate;
	private long balancePayment;
	private long extraPayment;
	private Shop shop;
	private Address address;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(int mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	public Date getBookingDate() {
		return bookingDate;
	}
	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}
	public long getAdvanceAmount() {
		return advanceAmount;
	}
	public void setAdvanceAmount(long advanceAmount) {
		this.advanceAmount = advanceAmount;
	}
	public Date getLastDueDate() {
		return lastDueDate;
	}
	public void setLastDueDate(Date lastDueDate) {
		this.lastDueDate = lastDueDate;
	}
	public Date getNextDueDate() {
		return nextDueDate;
	}
	public void setNextDueDate(Date nextDueDate) {
		this.nextDueDate = nextDueDate;
	}
	public long getBalancePayment() {
		return balancePayment;
	}
	public void setBalancePayment(long balancePayment) {
		this.balancePayment = balancePayment;
	}
	public long getExtraPayment() {
		return extraPayment;
	}
	public void setExtraPayment(long extraPayment) {
		this.extraPayment = extraPayment;
	}
	public Shop getShop() {
		return shop;
	}
	public void setShop(Shop shop) {
		this.shop = shop;
	}
	public Address getAddress() {
		return address;
	}
	public void setAddress(Address address) {
		this.address = address;
	}
	
	
	
	
}
